/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { Mkc } from './Mkc';
export * as factories from './factories';
export { Mkc__factory } from './factories/Mkc__factory';
