# You specify the stages.
# Those are the steps that GitLab will go through 
# Order matters a lot.
stages:
  #Self made at every commit
  - staging 
  #Must be triggered mannualy 
  - production
      
deploy_to_preprod:
  stage: staging
  retry: 1
  only:
    - main
  except:
    - schedules
  script:
    - cd ..
    - mkdir ~/.ssh
    - cp $SSH_DEV_BACKEND ~/.ssh/id_rsa
    - chmod 600 ~/.ssh/id_rsa
    - ssh -oStrictHostKeyChecking=no -i ~/.ssh/id_rsa admin@$IP_DEV 'echo "Command from GITLAB CI for dev env CME Backend" > /tmp/gitlab.tmp'
    - scp cme-backend/deploy.sh admin@$IP_DEV:/home/admin/deploy.sh
    - scp -r cme-backend/apps admin@$IP_DEV:/home/admin/cme-backend/apps
    - ssh admin@$IP_DEV 'sudo cp -R /home/admin/cme-backend/apps /home/gitlab-ci/cme-backend/apps'
    - ssh admin@$IP_DEV 'sudo chown gitlab-ci:gitlab-ci /home/gitlab-ci/cme-backend'

deploy_to_prod:
  stage: production
  retry: 1
  only:
    - main
  except:
    - schedules
  script:
    - cd ..
    - mkdir ~/.ssh
    - cp $SSH_PROD_BACKEND ~/.ssh/id_rsa
    - chmod 600 ~/.ssh/id_rsa
    - ssh -oStrictHostKeyChecking=no -i ~/.ssh/id_rsa admin@$IP_PROD 'echo "Command from GITLAB CI for dev env CME Backend" > /tmp/gitlab.tmp'
    - scp cme-backend/deploy.sh admin@$IP_PROD:/home/admin/deploy.sh
    - scp -r cme-backend/apps admin@$IP_PROD:/home/gitlab-ci/cme-backend/apps
    - ssh admin@$IP_PROD 'sudo chown gitlab-ci:gitlab-ci /home/gitlab-ci/cme-backend'
  when: manual
